### ISSUE TITLE
# Ensure Go 1.21 or higher

### ISSUE THREAD

**Issue by proother** [EbrahimTahernejad/sing-box-lib#3]
Please ensure Go 1.21 or higher
```
`go-version: '1.21'
```
The error you are encountering indicates that the quic-go module you are using is incompatible with the version of Go you have set up. Specifically, the errors show issues with type mismatches and undefined symbols in the quic-go library.

To resolve this, ensure that you are using the correct version of Go as required by the quic-go library, or update the library version if a newer one is available that supports your Go version. Here's how you can modify your GitHub Actions workflow to ensure compatibility:

Ensure the correct Go version is used: Make sure you are using Go 1.21 or higher, as the clientSessionCache is defined in Go 1.21 and later.

**Comment by proother** [comment]
here is /SagerNet/sing-box 

```
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
```
